name: build

on: [push, pull_request]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2.4.0
    
    - name: Restore NuGet packages
      run: nuget restore
    
    - name: Setup Conan
      run: pip install conan

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true

    - name: Conan Install
      run: msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ./CONAN_INSTALL

    - name: Publish
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ./DEPLOY

    - name: Clean up
      run: |
        cd build
        cd Release
        del *.pdb
        del *.lib
        del *.exp
        del xaudio2_9redist.dll

    - name: Store Build
      uses: actions/upload-artifact@v2
      with: 
          name: Magpie-Auto-Build
          path: build\Release
